import React from 'react';
import { Brain, Map, BookOpen, Sparkles, ArrowRight, Check, Code2, Database, Zap, Shield } from 'lucide-react';
import Link from 'next/link';

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-white">
      {/* Navigation */}
      <nav className="border-b border-slate-800 bg-slate-900/50 backdrop-blur-sm fixed w-full z-50">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-gradient-to-br from-orange-500 to-red-600 p-2 rounded-lg">
              <Brain className="w-6 h-6" />
            </div>
            <span className="text-2xl font-bold bg-gradient-to-r from-orange-400 to-red-500 bg-clip-text text-transparent">
              LearnForge
            </span>
          </div>
          <div className="flex gap-4">
            <Link href="/sign-in">
              <button className="px-4 py-2 text-slate-300 hover:text-white transition">
                Sign In
              </button>
            </Link>
            <Link href="/sign-up">
              <button className="px-6 py-2 bg-gradient-to-r from-orange-500 to-red-600 rounded-lg font-semibold hover:shadow-lg hover:shadow-orange-500/50 transition">
                Get Started
              </button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-7xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-slate-800/50 rounded-full border border-slate-700 mb-6">
            <Sparkles className="w-4 h-4 text-orange-400" />
            <span className="text-sm text-slate-300">AI-Powered Learning Platform</span>
          </div>
          
          <h1 className="text-6xl md:text-7xl font-bold mb-6 leading-tight">
            Forge Your Knowledge with{' '}
            <span className="bg-gradient-to-r from-orange-400 via-red-500 to-pink-500 bg-clip-text text-transparent">
              AI-Powered Learning
            </span>
          </h1>
          
          <p className="text-xl text-slate-400 mb-10 max-w-3xl mx-auto">
            Create personalized study roadmaps and intelligent quizzes tailored to your learning style. Master any subject faster with AI as your guide.
          </p>
          
          <div className="flex gap-4 justify-center flex-wrap">
            <Link href="/sign-up">
              <button className="px-8 py-4 bg-gradient-to-r from-orange-500 to-red-600 rounded-xl font-semibold text-lg hover:shadow-2xl hover:shadow-orange-500/50 transition flex items-center gap-2 cursor-pointer">
                Start Learning Free
                <ArrowRight className="w-5 h-5" />
              </button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6 bg-slate-900/50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Everything You Need to{' '}
              <span className="bg-gradient-to-r from-orange-400 to-red-500 bg-clip-text text-transparent">
                Excel
              </span>
            </h2>
            <p className="text-xl text-slate-400">
              Powerful features to accelerate your learning journey
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-8 hover:border-orange-500/50 transition group">
              <div className="bg-gradient-to-br from-orange-500 to-red-600 w-14 h-14 rounded-xl flex items-center justify-center mb-6 group-hover:shadow-lg group-hover:shadow-orange-500/50 transition">
                <Map className="w-7 h-7" />
              </div>
              <h3 className="text-2xl font-bold mb-4">AI Roadmaps</h3>
              <p className="text-slate-400 mb-6">
                Get personalized, step-by-step study plans generated by AI based on your goals and current knowledge level.
              </p>
              <ul className="space-y-2 text-slate-300">
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  Custom learning paths
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  Progress tracking
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  Adaptive difficulty
                </li>
              </ul>
            </div>

            {/* Feature 2 */}
            <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-8 hover:border-orange-500/50 transition group">
              <div className="bg-gradient-to-br from-orange-500 to-red-600 w-14 h-14 rounded-xl flex items-center justify-center mb-6 group-hover:shadow-lg group-hover:shadow-orange-500/50 transition">
                <BookOpen className="w-7 h-7" />
              </div>
              <h3 className="text-2xl font-bold mb-4">Smart Quizzes</h3>
              <p className="text-slate-400 mb-6">
                Test your knowledge with AI-generated quizzes that adapt to your learning pace and identify weak areas.
              </p>
              <ul className="space-y-2 text-slate-300">
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  Instant feedback
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  Detailed explanations
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  Performance analytics
                </li>
              </ul>
            </div>

            {/* Feature 3 */}
            <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-8 hover:border-orange-500/50 transition group">
              <div className="bg-gradient-to-br from-orange-500 to-red-600 w-14 h-14 rounded-xl flex items-center justify-center mb-6 group-hover:shadow-lg group-hover:shadow-orange-500/50 transition">
                <Brain className="w-7 h-7" />
              </div>
              <h3 className="text-2xl font-bold mb-4">AI Assistant</h3>
              <p className="text-slate-400 mb-6">
                Get instant answers to your questions and personalized study tips from our intelligent AI tutor.
              </p>
              <ul className="space-y-2 text-slate-300">
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  24/7 availability
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  Context-aware help
                </li>
                <li className="flex items-center gap-2">
                  <Check className="w-5 h-5 text-orange-400" />
                  Multi-subject support
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-5xl font-bold mb-6">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-xl text-slate-400 mb-10">
            Experience personalized, AI-powered education designed to help you master any subject efficiently.
          </p>
          <Link href="/sign-up">
            <button className="px-10 py-5 bg-gradient-to-r from-orange-500 to-red-600 rounded-xl font-semibold text-lg hover:shadow-2xl hover:shadow-orange-500/50 transition inline-flex items-center gap-2 cursor-pointer">
              Get Started for Free
              <ArrowRight className="w-5 h-5" />
            </button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-800 py-12 px-6 bg-slate-900/50">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <div className="bg-gradient-to-br from-orange-500 to-red-600 p-2 rounded-lg">
              <Brain className="w-5 h-5" />
            </div>
            <span className="text-xl font-bold">LearnForge</span>
          </div>
          <p className="text-slate-400 text-sm">
            © 2025 LearnForge. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}